<?xml version="1.0"?>
<robot name="wheelchair_bot" xmlns:xacro="http://www.ros.org/xacro">

  <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>

  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="chassis_length" value="0.6" />
  <xacro:property name="chassis_width" value="0.4" />
  <xacro:property name="chassis_height" value="0.2" />
  <xacro:property name="chassis_mass" value="10" />

  <xacro:property name="wheel_radius" value="0.15" /> 
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="wheel_mass" value="1" />
  
  <xacro:property name="caster_radius" value="0.05" />
  <xacro:property name="caster_mass" value="0.1" />

  <xacro:property name="lidar_size" value="0.05" />
  <xacro:property name="lidar_mass" value="0.1" />

  <!-- ===================== -->
  <!--  DRIVE WHEEL MACRO   -->
  <!-- ===================== -->
  <xacro:macro name="drive_wheel" params="prefix side_y">
    <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${wheel_mass}"/>
        <origin rpy="${PI/2} 0 0" xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="0 ${side_y * (chassis_width/2 + wheel_width/2)} 0" rpy="0 0 0"/> 
      <axis xyz="0 1 0"/>
    </joint>
    
    <gazebo reference="${prefix}_wheel_link">
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <!-- ===================== -->
  <!--  CASTER WHEEL MACRO  -->
  <!-- ===================== -->
  <xacro:macro name="caster_wheel" params="prefix x_pos">
    <link name="${prefix}_caster_link">
      <visual>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="Grey"><color rgba="0.5 0.5 0.5 1.0"/></material>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="${caster_mass}"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    
    <joint name="${prefix}_caster_joint" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_caster_link"/>
      <origin xyz="${x_pos} 0 ${caster_radius - wheel_radius}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}_caster_link">
      <material>Gazebo/Grey</material>
      <mu1>0.01</mu1>
      <mu2>0.01</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
    </gazebo>
  </xacro:macro>

  <!-- ===================== -->
  <!--       BASE LINK       -->
  <!-- ===================== -->
  <link name="base_link">
    <visual>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <material name="green"><color rgba="0.0 0.8 0.2 1.0"/></material>
    </visual>
    <collision>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- ===================== -->
  <!--   FIXED LIDAR HEIGHT  -->
  <!-- ===================== -->
  <xacro:VLP-16 parent="base_link" name="velodyne" topic="/velodyne_points" hz="10" samples="440" min_range="0.1">
    <!-- LIDAR NOW RAISED ABOVE THE ROBOT BODY -->
    <origin xyz="${chassis_length/2 - 0.05} 0 ${wheel_radius + chassis_height + 0.25}" rpy="0 0 0" />
  </xacro:VLP-16>

  <!-- ===================== -->
  <!--   WHEELS & CASTERS   -->
  <!-- ===================== -->
  <xacro:drive_wheel prefix="left" side_y="1" />
  <xacro:drive_wheel prefix="right" side_y="-1" />
  <xacro:caster_wheel prefix="front" x_pos="${chassis_length/2 - caster_radius}" />
  <xacro:caster_wheel prefix="rear" x_pos="${-chassis_length/2 + caster_radius}" />

  <!-- ===================== -->
  <!--    DRIVE PLUGIN       -->
  <!-- ===================== -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100</updateRate>

      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${chassis_width + wheel_width}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <wheelTorque>20</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>

      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>

      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>

      <publishWheelTF>false</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>true</publishWheelJointState>

      <legacyMode>false</legacyMode>
    </plugin>
  </gazebo>

</robot>

